# api-manager — PRODUCTION override
# Hardcoded routes (container DNS). JWT secret env var'dan.

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: security-service
              uri: http://security:8002
              predicates:
                - Path=/security/**

            - id: product-service-public
              uri: http://pos-product-manager:8001
              predicates:
                - Path=/product/api/v1/public/**

            - id: product-service-private
              uri: http://pos-product-manager:8001
              predicates:
                - Path=/product/**

            - id: notification-service
              uri: http://notification-service:8004
              predicates:
                - Path=/notification/**

            - id: hr-manager-service
              uri: http://hr-manager:8005
              predicates:
                - Path=/hr/**

jwt:
  secret: ${JWT_SECRET}
