# security servisi — PRODUCTION override

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: false

  sql:
    init:
      mode: never

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
